/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import javax.swing.JMenu;
import javax.swing.JMenuItem;
import main.App;

/**
 *
 * @author STMIK-VII
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }
    
    public BarangView barangView;
    public StokView stokView;
    public FMasukView fMasukView;
    public FKeluarView fKeluarView;
    public UserView userView;

    public JMenuItem getItemBarang() {
        return itemBarang;
    }

    public void setItemBarang(JMenuItem itemBarang) {
        this.itemBarang = itemBarang;
    }

    public JMenuItem getItemFKeluar() {
        return itemFKeluar;
    }

    public void setItemFKeluar(JMenuItem itemFKeluar) {
        this.itemFKeluar = itemFKeluar;
    }

    public JMenuItem getItemFMasuk() {
        return itemFMasuk;
    }

    public void setItemFMasuk(JMenuItem itemFMasuk) {
        this.itemFMasuk = itemFMasuk;
    }

    public JMenuItem getItemStok() {
        return itemStok;
    }

    public void setItemStok(JMenuItem itemStok) {
        this.itemStok = itemStok;
    }

    public JMenu getjMenu3() {
        return jMenu3;
    }

    public void setjMenu3(JMenu jMenu3) {
        this.jMenu3 = jMenu3;
    }

    public JMenu getMenuFaktur() {
        return menuFaktur;
    }

    public void setMenuFaktur(JMenu menuFaktur) {
        this.menuFaktur = menuFaktur;
    }

    public JMenu getMenuStok() {
        return menuStok;
    }

    public void setMenuStok(JMenu menuStok) {
        this.menuStok = menuStok;
    }

    public JMenu getMenuUser() {
        return menuUser;
    }

    public void setMenuUser(JMenu menuUser) {
        this.menuUser = menuUser;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        layarUtama = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuStok = new javax.swing.JMenu();
        itemBarang = new javax.swing.JMenuItem();
        itemStok = new javax.swing.JMenuItem();
        menuFaktur = new javax.swing.JMenu();
        itemFMasuk = new javax.swing.JMenuItem();
        itemFKeluar = new javax.swing.JMenuItem();
        menuUser = new javax.swing.JMenu();
        itemUser = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                formComponentRemoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        layarUtama.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layarUtamaLayout = new javax.swing.GroupLayout(layarUtama);
        layarUtama.setLayout(layarUtamaLayout);
        layarUtamaLayout.setHorizontalGroup(
            layarUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layarUtamaLayout.createSequentialGroup()
                .addContainerGap(307, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layarUtamaLayout.setVerticalGroup(
            layarUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        getContentPane().add(layarUtama, java.awt.BorderLayout.CENTER);

        menuStok.setText("Stok");
        menuStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStokActionPerformed(evt);
            }
        });

        itemBarang.setText("Barang");
        itemBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBarangActionPerformed(evt);
            }
        });
        menuStok.add(itemBarang);

        itemStok.setText("Stok Warna");
        itemStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStokActionPerformed(evt);
            }
        });
        menuStok.add(itemStok);

        jMenuBar1.add(menuStok);

        menuFaktur.setText("Faktur");

        itemFMasuk.setText("Faktur Masuk");
        itemFMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFMasukActionPerformed(evt);
            }
        });
        menuFaktur.add(itemFMasuk);

        itemFKeluar.setText("Faktur Keluar");
        itemFKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFKeluarActionPerformed(evt);
            }
        });
        menuFaktur.add(itemFKeluar);

        jMenuBar1.add(menuFaktur);

        menuUser.setText("User");

        itemUser.setText("User");
        itemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUserActionPerformed(evt);
            }
        });
        menuUser.add(itemUser);

        jMenuBar1.add(menuUser);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuStokActionPerformed

    private void itemBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBarangActionPerformed
        // TODO add your handling code here:
        if (barangView == null) {
            barangView = new BarangView();
            layarUtama.add(barangView);
        } else {
            barangView.toFront();
        }
        barangView.setVisible(true);
    }//GEN-LAST:event_itemBarangActionPerformed

    private void itemStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemStokActionPerformed
        // TODO add your handling code here:
        if (stokView == null) {
            stokView = new StokView();
            layarUtama.add(stokView);
        } else {
            stokView.toFront();
        }
        stokView.setVisible(true);
    }//GEN-LAST:event_itemStokActionPerformed

    private void itemFMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFMasukActionPerformed
        // TODO add your handling code here:
        if (fMasukView == null) {
            fMasukView = new FMasukView();
            layarUtama.add(fMasukView);
        } else {
            fMasukView.toFront();
        }
        fMasukView.setVisible(true);
    }//GEN-LAST:event_itemFMasukActionPerformed

    private void itemFKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFKeluarActionPerformed
        // TODO add your handling code here:
        if (fKeluarView == null) {
            fKeluarView = new FKeluarView();
            layarUtama.add(fKeluarView);
        } else {
            fKeluarView.toFront();
        }
        fKeluarView.setVisible(true);
    }//GEN-LAST:event_itemFKeluarActionPerformed

    private void itemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUserActionPerformed
        // TODO add your handling code here:
        if (userView == null) {
            userView = new UserView();
            layarUtama.add(userView);
        } else {
            userView.toFront();
        }
        userView.setVisible(true);
    }//GEN-LAST:event_itemUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginView().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentRemoved

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemBarang;
    private javax.swing.JMenuItem itemFKeluar;
    private javax.swing.JMenuItem itemFMasuk;
    private javax.swing.JMenuItem itemStok;
    private javax.swing.JMenuItem itemUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane layarUtama;
    private javax.swing.JMenu menuFaktur;
    private javax.swing.JMenu menuStok;
    private javax.swing.JMenu menuUser;
    // End of variables declaration//GEN-END:variables
}
